// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBhnf-YFvd3_e_5zcsmsqJWWoLm4qZfOw',
    appId: '1:48446529351:web:82d6c99cd17be8b609b662',
    messagingSenderId: '48446529351',
    projectId: 'todo-list-provider-38b1c',
    authDomain: 'todo-list-provider-38b1c.firebaseapp.com',
    storageBucket: 'todo-list-provider-38b1c.appspot.com',
    measurementId: 'G-L4LVM1S1DS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2Ge-pmv_riA6F-e6AaQzETBxUB3Nvf4I',
    appId: '1:48446529351:android:67435c65feb22b0009b662',
    messagingSenderId: '48446529351',
    projectId: 'todo-list-provider-38b1c',
    storageBucket: 'todo-list-provider-38b1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZvs4XdztbcJzmisexc5WjWti9KPLM9jM',
    appId: '1:48446529351:ios:2002aa7933e2235a09b662',
    messagingSenderId: '48446529351',
    projectId: 'todo-list-provider-38b1c',
    storageBucket: 'todo-list-provider-38b1c.appspot.com',
    iosClientId: '48446529351-dc3bjifp04k6eab01i7rpgi3d0v42frr.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZvs4XdztbcJzmisexc5WjWti9KPLM9jM',
    appId: '1:48446529351:ios:7c3e8d755b391c1b09b662',
    messagingSenderId: '48446529351',
    projectId: 'todo-list-provider-38b1c',
    storageBucket: 'todo-list-provider-38b1c.appspot.com',
    iosClientId: '48446529351-guspkgis06ukt0f17dsfgck9cmtpk8or.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoListProvider.RunnerTests',
  );
}
